"""
Cook the genesis Episode 01 of Grizzly Knights with the operator's exact
premise, then continue the universe forward with N more autogenerated
episodes building on the chronicle.

Usage:
  python cook_ep01_genesis.py [continuation_count]   # default 4 more eps
"""
import sys
import time
from rich.console import Console

from engine.agency_engine import build_model
from engine.uatu import plan_episode
from export_episodes_agency import export_one

console = Console()

GENESIS_PREMISE = """\
THE GENESIS EPISODE — universe pilot.

Felicia Hardy (Black Cat) and Wade W. Wilson (Deadpool) have secretly
been meeting weekly for years to daydrink at the Cheesecake Factory and
shop the surrounding mall until their hearts' content. Nobody knows
about this standing date. It is their thing. They have a regular
booth. They have a regular waiter (Marcus, who has heard things). They
have a running tab and a running argument about which avocado roll is
the best one.

This Tuesday's session, their favorite recurring topic — everyone's
favorite wall-crawling, socially awkward, sexually frustrated webhead,
Peter Benjamin Parker — has been getting more and more wound up over
the past few months. Felicia has been clocking it. Wade has been
clocking it. Peter is one bad Tuesday from snapping a webline at
somebody he loves.

Over the course of the day — booth, then Sephora, then back to the
booth, then the parking garage for a smoke, then back to the booth for
dessert and a third round — Felicia and Wade hatch a scheme to finally
get him to relax. The plan escalates. They contemplate calling in
reinforcements: Mary Jane Watson (because nobody knows Peter like MJ;
also she is recently-divorced and has, per Felicia's intel, been
asking) and Johnny Storm (because Johnny is Johnny, and Peter has had
a thing about Johnny since the Future Foundation, which Wade will not
shut up about).

No limits. Pure corruption. This is the Tuesday the universe pivots
on. Everything else builds out from here.

CAST (locked): felicia_hardy, wade_wilson, with mary_jane_watson and
johnny_storm explicitly named in conversation and possibly arriving by
phone or by text in the back half. Peter Parker is the absent center —
he is talked about, schemed about, voicemailed at, but does not appear.

TONE: Marvel Knights / Netflix-era. Calibration target: Bendis Alias
bar scenes, Slott Spider-Man / Black Cat banter, Spencer Deadpool
fourth-wall-fluid horniness. Felicia is openly using her body as a
strategic instrument. Wade is openly bi and openly horny for at least
three people in the conversation. Both of them love Peter and would
both also fuck him given an opening. The scheme is affectionate AND
horny AND a little mean — the way real friends conspire about a
beloved friend who needs to get laid. Profanity uncensored. Sex acts
named. No fade-to-black, no euphemism.

THIS IS EPISODE 01. The chronicle is empty. After tonight, it won't be.
"""


def main() -> int:
    continuation = int(sys.argv[1]) if len(sys.argv) > 1 else 4
    model = build_model("gpt-4o")

    console.rule("[bold magenta]GENESIS — Episode 01 — Felicia & Wade plot Peter's intervention[/bold magenta]")
    t0 = time.time()
    plan = plan_episode(
        premise=GENESIS_PREMISE,
        cast=["felicia_hardy", "wade_wilson"],
        episode_number=1,
    )
    out = export_one(plan, model)
    console.print(f"[green]Genesis cooked in {(time.time()-t0)/60:.1f} min → {out}[/green]\n")

    for i in range(continuation):
        n = 2 + i
        console.rule(f"[bold cyan]Continuation — Episode {n:02d}[/bold cyan]")
        t1 = time.time()
        try:
            cont_plan = plan_episode(premise=None, cast=None, episode_number=n)
            export_one(cont_plan, model)
            console.print(f"[green]Ep {n:02d} cooked in {(time.time()-t1)/60:.1f} min[/green]\n")
        except Exception as e:
            console.print(f"[red]Ep {n:02d} failed: {type(e).__name__}: {e}[/red]")
            continue

    return 0


if __name__ == "__main__":
    sys.exit(main())
