#!/usr/bin/env python3
"""Civilian layer — the functional population the heroes move through.

Tier 3: NOT studied subjects, NOT deep dossiers. Light templated sketches (name, role,
neighborhood, a few sentences of personality, a quirk, a voice) generated by a FREE model.
Kept in universe/civilians/ — a SEPARATE folder so they never contaminate the uniform-depth
principal/supporting research dataset in universe/characters/.

These give the world a crowd: people working restaurants, driving cabs, walking dogs — the
texture that makes 270 notable figures a city instead of a roster.
"""
import os, json, time, random, urllib.request, urllib.error

ROOT = "/Users/rbhanson/fanfic"
OUT = f"{ROOT}/universe/civilians"
os.makedirs(OUT, exist_ok=True)

def key():
    for line in open(f"{ROOT}/.env"):
        if line.startswith("openrouter_key="):
            return line.split("=", 1)[1].strip().strip('"').strip("'")
    return ""
KEY = key()
FREE = ["meta-llama/llama-3.3-70b-instruct:free", "openai/gpt-oss-120b:free", "google/gemma-4-31b-it:free"]

ROLES = ["short-order cook", "barista", "NYPD beat cop", "yellow-cab driver", "ER nurse",
    "bodega owner", "subway busker", "construction foreman", "public-school teacher", "dive bartender",
    "halal cart vendor", "sanitation worker", "dock worker", "FDNY firefighter", "tabloid stringer",
    "building superintendent", "bike messenger", "deli counterman", "MTA booth clerk", "street pretzel vendor",
    "pawnshop owner", "tattoo artist", "EMT", "night-shift security guard", "laundromat owner",
    "florist", "shoe-shine", "newsstand owner", "ferry deckhand", "diner waitress"]
HOODS = ["Hell's Kitchen", "Harlem", "Lower East Side", "Astoria", "Bed-Stuy", "the South Bronx",
    "Chinatown", "Midtown", "Washington Heights", "Red Hook", "Flushing", "the Financial District",
    "Greenwich Village", "Sunset Park", "Mott Haven"]

def make(role, hood):
    sysmsg = ("You invent ONE ordinary New Yorker — a civilian, not a hero. Realistic, grounded, "
              "diverse, a little specific. Output ONLY compact JSON.")
    usr = (f"A {role} in {hood}. Output JSON: {{\"name\":\"full name\",\"age\":int,\"role\":\"{role}\","
           f"\"neighborhood\":\"{hood}\",\"personality\":\"2-3 sentences, grounded and specific\","
           "\"quirk\":\"one memorable detail\",\"voice\":\"how they talk in one phrase\","
           "\"daily\":\"their typical day in one line\"}. No preamble.")
    body = json.dumps({"messages": [{"role": "system", "content": sysmsg}, {"role": "user", "content": usr}],
                       "max_tokens": 300, "temperature": 0.9}).encode()
    for m in FREE:
        b = json.loads(body); b["model"] = m
        try:
            req = urllib.request.Request("https://openrouter.ai/api/v1/chat/completions",
                data=json.dumps(b).encode(),
                headers={"Authorization": "Bearer " + KEY, "Content-Type": "application/json"})
            with urllib.request.urlopen(req, timeout=60) as r:
                j = json.load(r)
            txt = (j.get("choices", [{}])[0].get("message", {}).get("content") or "").strip()
            txt = txt.replace("```json", "").replace("```", "")
            s, e = txt.find("{"), txt.rfind("}")
            if s >= 0 and e > s:
                obj = json.loads(txt[s:e+1]); obj["tier"] = "civilian"
                return obj
        except urllib.error.HTTPError as ex:
            if ex.code == 429: time.sleep(15)
        except Exception:
            pass
    return None

def main(n=60):
    made = 0
    combos = [(r, random.Random(i).choice(HOODS)) for i, r in enumerate(random.Random(7).choices(ROLES, k=n))]
    for i, (role, hood) in enumerate(combos):
        c = make(role, hood)
        if not c or not c.get("name"):
            continue
        stem = "".join(ch.lower() if ch.isalnum() else "_" for ch in c["name"]).strip("_")
        if not stem or os.path.exists(f"{OUT}/{stem}.json"):
            stem = f"{stem}_{i}"
        json.dump(c, open(f"{OUT}/{stem}.json", "w"), indent=2)
        made += 1
        print(f"[{made}] {c['name']} — {c['role']}, {c['neighborhood']}", flush=True)
        time.sleep(2)
    print(f"CIVILIANS DONE: {made} written to {OUT}", flush=True)

if __name__ == "__main__":
    import sys
    main(int(sys.argv[1]) if len(sys.argv) > 1 else 60)
